### ISSUE TITLE
Update docker container

### ISSUE THREAD

**Issue by Ephigenia** [Buktahula/hassio-addons#1]
The docker container "buktahula/lgess-*" seem to be outdated since https://github.com/gluap/pyess was released with a fix. Also there’s no Dockerfile to be found to be able to inspect the contents of the docker container.

**Comment by Buktahula** [comment]
Hey thanks for the tip, I'm new here to Github and HomeAssistant. You can find the Dockerfile at "https://github.com/Buktahula/hassio-addons/tree/main/LG_ESS". The container is uploaded directly to Dockerhub as soon as a new release is created, and the container only installs the pyess itself, which should therefore always be up to date. Are there problems with the installation?

**Comment by Ephigenia** [comment]
> Hey thanks for the tip, I'm new here to Github and HomeAssistant. You can find the > Dockerfile at "https://github.com/Buktahula/hassio-addons/tree/main/LG_ESS".

Great thanks for pointing me to the Dockerfile that helped a lot in understanding how it works! Also I’m happy to help you with any setups and testing as I want to be able to use this integration for displaying my LG ESS Setup in my home-assistant energy dashboard.

> The container is uploaded directly to Dockerhub as soon as a new release is created, and the container only installs the pyess itself, which should therefore always be up to date.

That's partly right. The docker container is build upon every release that is created for the hassio-addons repo. Only at this time the latest version of pyess is used in the docker container. The pyess version inside of the container is not updated or replaced it sticks to the version that was present on build-time.

So for the current state the docker container contains the pyess version which was the latest 24 days ago. It's not the latest anymore! There must be a new release created for the "Buktahula/hassio-addons" repo in order to update the docker image on docker hup. Not sure how updating or having an update notification in home assistant will work then. Maybe the add-on has to be re-installed.

It would help if you create a new release or push a newer version of the docker image to dockerhub.

I need this in Order to be able to test the fix for https://github.com/gluap/pyess/issues/14

> Are there problems with the installation?

Some. I hope after testing the fix for https://github.com/gluap/pyess/issues/14 the sensors can be used in the energy dashboard. I checked some of the documentation for the energy dashboard and the values require the correct unit to be used and long-term statistics enabled.

Another problem is that the sensors don’t have unique names which is a hard requirement for all entities in home-assistant. Maybe that's not a problem of this add-on but of pyess. The problem is described here: https://www.home-assistant.io/faq/unique_id/

But let's see how it works after the update of the docker-containers.

**Comment by Buktahula** [comment]
New Release is deployed. Tomorrow i put my template sensor config to this repo, so youncan download it, or you can look how itsworks on my Dashboard ( its german wording)

**Comment by Buktahula** [comment]
Hmmm Something went wrong . Sorry , ist my first addon with Git actions , the Action the action dont deploy the Container with the right tag.

**Comment by Buktahula** [comment]
I've looked at everything now and I noticed that it was always the latest version of pyess. The article you are referring to is from 2022 not 2023. I have now provided the container for you under version 0.0.5, and I have also added a link to the readme to an example sensor.yaml, with this yaml I operate the whole thing successfully in my dashboard. I think I can close the bug now

**Comment by Ephigenia** [comment]
> I've looked at everything now and I noticed that it was always the latest version of pyess.

You’re right!

I’ve update the container and also added the provided example template and sensor values and it works like charm now! Thank you!
