### ISSUE TITLE
Fetch password error

### ISSUE THREAD

**Issue by metalux2030** [Buktahula/hassio-addons#2]
Hi Buktahula,

many thanks for creating the addon. Really looking forward to use it. Was looking for so long to get the data out of my LG ESS to use it in HA. I tried to get the password (is it equal with the installer password?) of my ESS and run the Python App as discribed. but I got the following error message. May you can give me the hint how I can fix it. Thanks in advance.

`Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  _main_.__dict__)
  File "<string>", line 1
    pip install pyess
        ^
SyntaxError: invalid syntax

[Program finished]`

Best
Jens

**Comment by metalux2030** [comment]
Was my beginners fault. Wass using the interpreter not the terminal :)

**Comment by Buktahula** [comment]
Ohhh okay . I will update the Readme in the next days , so every other cant run into Thing fault .
