### ISSUE TITLE
Error Message, Sever stopps

### ISSUE THREAD

**Issue by metalux2030** [Buktahula/hassio-addons#3]
Hey,

sorry to coming back with the next hurdle I'm fighting with. 

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[22:49:41] INFO: Initialize the essmqtt configuration...
INFO:pyess.aio_ess:fetching auth key
Traceback (most recent call last):
  File "/usr/local/bin/essmqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 103, in main
    asyncio.run(_main(arguments))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 176, in _main
    await launch_main_loop(args, ess, handle_control, switch_active, switch_fastcharge, switch_winter)
  File "/usr/local/lib/python3.8/site-packages/pyess/essmqtt.py", line 195, in launch_main_loop
    async with Client(args.mqtt_server, port=args.mqtt_port, logger=logger, username=args.mqtt_user,
  File "/usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py", line 822, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py", line 390, in connect
    raise MqttError(str(error)) from None
asyncio_mqtt.error.MqttError: [Errno -2] Name does not resolve
/usr/local/lib/python3.8/site-packages/pyess/aio_ess.py:205: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa7ffd850>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fa800fdc0>, 1410188.288722379)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fa7fe3220>
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

Happy if anybody could help me.

Best
Jens

**Comment by Buktahula** [comment]
Have you installed the mqtt addon? If yes, check your configuration.

**Comment by Buktahula** [comment]
It seems that you put the wrong mqtt Server in your configuration.

**Comment by metalux2030** [comment]
Yep, was a configuration problem wihe the mqqt Server. Made it and everything is running smoothly. 
great Work @Buktahula

**Comment by andrebraun2011** [comment]
@metalux2030 could you please describe what was done to fix this issue. I am getting nearly the same failure
