### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tvilhu** [Buktahula/hassio-addons#5]
There is a typo in the docker code that names sensors Ess/common/BATT/today_batt_discharge_enery and Ess/common/LOAD/today_batt_discharge_enery.. Since these do not match with yaml config you get sensors with correct values but incorrect type and cannot for example use today's discharged energy in the HA energy card since according to HA there is no such energy measurement.

**Comment by tvilhu** [comment]
This issue has now been fixed in pyess so all we need is updated pyess and release updated version of this addon.

**Comment by Buktahula** [comment]
the new version is available
