### ISSUE TITLE
New writable options?

### ISSUE THREAD

**Issue by tvilhu** [Buktahula/hassio-addons#6]
Would it be possible to add write to grid feed in? Since energy spot prices dip below zero i would like to stop the grid feed if price is too low. Also option to enable/disable battery would be nice since that ESS system does not automatically optimize battery usage for expensive hours.

**Comment by Buktahula** [comment]
please ask the Developer of the pyess. https://github.com/gluap/pyess

my git ist only the addon for hassio based in the pyess
