### ISSUE TITLE
Instructions to add to home assistant? 

### ISSUE THREAD

**Issue by crightonsetchfield** [Buktahula/hassio-addons#7]
Hello, i know this is a bit basic, but i cannot see this add on in the add on section of home assistant, i assume that i have to just add it as a docker container alongside? I have supervised and i read that it is possible to do that.. any quick tips or pointers?

**Comment by crightonsetchfield** [comment]
I have home assistant supervised, running on debian 12 on a pc.

**Comment by Buktahula** [comment]
Hi,
To add my GitHub repository to your Home Assistant addon section, follow these steps:
 * Open Home Assistant and navigate to the "Addons" section.
 * Click on the three dots in the top right corner.
 * Select "Repositories."
 * Click the "Add" button and enter the URL of my GitHub repository.
Let me know if you have any questions.

**Comment by crightonsetchfield** [comment]
That's great, i'm sure i've done this before for something else, but i must have forgotten about the 3 dots option. Anyway, it's working now, i will continuw with the setup. I had some difficulty to figure out which url to use, but i eventually got to this: 
https://github.com/Buktahula/hassio-addons.git
and then i needed to restart home assistant and then search again in the addon store to get it.

**Comment by crightonsetchfield** [comment]
Hello again, i have had a little time to play with this, i previously was using grafana to view the output from LGESS, but this plug in going into Home assistant is much easier. The only thing i am missing is `ess/common/PV/pv3_voltage,ess/common/PV/pv3_power,ess/common/PV/pv3_current`   from    `hass_autoconfig_sensors:`    
Is it possible to add that to the next release? or can i add it locally only?  I don't know how to do pull request or anything like that. sorry

**Comment by savage8811** [comment]
> The only thing i am missing is `ess/common/PV/pv3_voltage,ess/common/PV/pv3_power,ess/common/PV/pv3_current` from `hass_autoconfig_sensors:`
> Is it possible to add that to the next release? or can i add it locally only?

You only need to add this to hass_autoconfig_sensors in addon configuration (restart HA)

**Comment by Buktahula** [comment]
You only need to add this to hass_autoconfig_sensors in addon configuration (restart HA)
