### ISSUE TITLE
Change Request: README - How to fetch the device password

### ISSUE THREAD

**Issue by aLimp86** [Buktahula/hassio-addons#8]
Hi all, 

I read about an even easier method to fetch the device password. You don’t have to use an android device at all. 
You can simply use your router to look up the MAC address of your LG ESS Solar power converter. The password is exactly that but without the colons. 

For the MAC address a3:4d:c2:03:0c:ef your password will be a34dc2030cef. That’s it. (Not my MAC address, only an example)

Best regards, 
Andy

**Comment by Buktahula** [comment]
I Edit the Readme with you method and my as second if yours not work
