### ISSUE TITLE
Remote Control Use of Battery

### ISSUE THREAD

**Issue by my-wheel** [Buktahula/hassio-addons#9]
In the LG ESS App I can switch On/Off the use of the battery.
Because I want add an automation in Home Assistant to charge a different battery during night,
I want to avoid that the second battery is charged from the LG battery.
For that, I would like to control the the use of battery in the LG ESS by a command from Home Assistant.

Is this already possible? Or would it be a Change Request?

**Comment by Buktahula** [comment]
Please contect the developper of the pyess https://github.com/gluap/pyess . This git is only the Addon for Home Assistent based one his work
